apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: y9p6hxffh-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/y9p6hxffh-java-springboot-gitops